[package]
name = "gatekeeper-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
gatekeeper = { path = "../gatekeeper" }
iroh = "0.91.0"
rand = "0.8.5"
tokio = { version = "1.47.1", features = ["full"] }
